### ISSUE TITLE
server attribute 'jobscript_max_size' not working properly. 

### ISSUE THREAD

**Issue by dinesh1306** [openpbs/openpbs#1711]
Steps to reproduce:

1. set 'jobscript_max_size' with some value
2. submit job with job-script have size more than settled jobscript_max_size expected is job should be rejected.
3. unset 'jobscript_max_size'
4. submit job with job-script have size more than settled jobscript_max_size expected is job should be submitted and running, but job gets terminated immediately with Job Exit status 127.

I submitted job with -koe option and keeping server and mom logs at high value and got error message in job error file that script file not available in /var/spool/pbs/mom_priv/jobs/ for resprctive job.

I restarted PBS server and submit new job with script, then job was running fine and finished normally.

**Comment by arungrover** [comment]
The issue is that when a job is rejected due to job script size exceeding jobscript_max_size server does not unlink the job from its list.
In fact, if you submit more than one job exceeding jobscript_max_size and then submit jobs that do not exceed job_script_size then all those jobs will not run because Server locates the wrong job from its new jobs list and attaches the new job script to old jobs.
